# Generated by Django 4.1.5 on 2023-03-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('tut', 'tutor'), ('stu', 'student')], default='', max_length=3),
        ),
    ]
