# Generated by Django 4.1.7 on 2023-03-29 00:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_increase_schedule_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tutorTimings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default='{}', size=None),
        ),
    ]
