# Generated by Django 4.1.7 on 2023-03-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_alter_request_student_alter_request_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted',
            field=models.CharField(choices=[('acc', 'accept'), ('dec', 'decline'), ('', 'none')], default='', max_length=3),
        ),
    ]
