# Generated by Django 4.1.7 on 2023-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_alter_request_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
