# Generated by Django 4.1.7 on 2023-04-28 05:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_classrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='tutorsAlreadyAccepted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
        ),
    ]
