# Generated by Django 4.1.7 on 2023-05-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0015_alter_classrequest_tutorsalreadyaccepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="bio", field=models.TextField(blank=True),
        ),
    ]
