# Generated by Django 4.1.7 on 2023-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0016_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="bio", field=models.TextField(default="No bio yet"),
        ),
    ]
